#121 키트 생성 모달 레이아웃 완성
ZZIPSA/kkuk-kkuk-fe pull request #122
Opened 2024-06-07 07:07 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #121
키트 생성 모달 레이아웃을 완성했습니다.

## 테스트 내용

`/kits/new` 에 들어가 우측 하단의 `open modal` 을 누르면 모달을 확인할 수 있습니다.

### 리뷰어에게
#### 리뷰하기 전

#### 리뷰 후

### 체크리스트

- [ ] 리뷰하는데 20분 이상 필요한가요? _20분 초과할 경우, 예상 리뷰 시간을 덧붙여주세요_
- [ ] 셀프 리뷰를 진행했습니다.
- [ ] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [ ] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-06-07 07:14 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +
모달 테스트 용으로 실제 배포시에는 삭제 후 배포해야합니다. 페이지 우측 하단에 있습니다.
- 모달 열기 전
  <img width="140" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/9de2c115-9bc9-46dc-b27d-78aa7dcadbe4">
- 모달 연 후 
  <img width="125" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/f6c90e85-9fbe-477f-8118-3fffcee311d7">

2024-06-07 07:15 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +}
성공 시 표출되는 모달입니다.
<img width="360" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/4ed23246-e0fd-47e5-b95d-44e54ca970a3">

2024-06-07 07:16 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +}
- 트위터 공유버튼
  <img width="52" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/5ad6ae4a-169f-46d2-a7f7-71f8736e6ade">
- 링크 복사 버튼
  <img width="51" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/28e4001d-986f-4c79-9725-596731e97240">
- 홈페이지로 이동 버튼
  <img width="155" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/3d315c26-8b7d-4850-a2b7-c21df560093d">
- 생성된 키트 페이지로 이동하는 버튼
  <img width="157" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/73c0614d-c497-4bbd-8327-2e10bb469d69">

2024-06-07 07:49 UTC, mdgarden requested changes
차안에서 급하게 본거라 예시로 써드린 리팩토링 수정안을 반영할 경우에는 꼭! 동작 확인 하셔서 수정부탁드립니다...🥹 이번주까지는 코드 리뷰만하고, 실기 확인은 테스트 진행하면서 별도로 진행하겠습니다.

2024-06-07 07:49 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +        𝕏
질문)
여기는 이미지가 아니고 폰트로 처리하신건가요? 이 𝕏라는 텍스트는 폰트나 사용자의 환경에 관계없이 항상 같은 표시가 보장되는건가요? 전에 𝕏 <- 이 표시가 무슨 폰트라고 들었던 것 같은데...제가 잘못알고있는거면 패스해주세욥!

2024-06-07 07:49 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +const getTwitterShareLink = (id: string) =>
메모) 여기서 수정할 부분은 아니나, 추후 랠리 공유 모달에서도 여기에 있는 함수들과 스타일들이 똑같이 쓰일 수 있어서 모듈화로 리팩토링도리 것 같습니다. 랠리 공유 모달에 관해서는 하루님께 현재 확인중입니다.

2024-06-07 07:49 UTC, mdgarden commented on app/kits/new/components/NewKitForm/index.tsx
> +  const [id, setId] = useState<string>('');
현재는 이 `id`가 단순히 `visible`의 용도로 사용되고 있는 것 같습니다.
테스트용이라고는 하나, 만약 다른 사람이 이 페이지를 작업하게 될 경우에는 `id`라는 요소가 헷갈릴 수 있을 것 같습니다. 다음과 같은 수정은 어떠실까요?

```tsx
export default function NewKitFort() {
  const [visibleTestModal, setVisibleTestModal] = useState<boolean>(false);

// ... 생략
  function onSubmit(data: FormValues) {
    setVisibleTestModal(!visibleTestModal)
   }
//...생략
}

2024-06-07 07:49 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +export default function SuccessModal({ id }: { id: string }) {
Modal에는 `visible`프롭으로 표시/비표시 상태를 컨트롤 하는 것이 일반적인 것으로 알고 있습니다. 하단의 코멘트 참조하셔서 `visible`을 받을 수 있도록 수정해주세요. `id`에 대한 정보와 표시/비표시에 대한 정보는 구분되어야할 것 같습니다.

2024-06-07 07:49 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +        <Buttons id={id} />
`id`프롭을 `kitId`로 변경해서 어떤 아이디를 받고 있는지 구체적으로 명시해주면 좋을 것 같습니다.

2024-06-07 07:49 UTC, mdgarden commented on lib/constants.ts
> +export const AUTO_TWEET = encodeURI('제가 만든 키트로 릴레이를 시작해보세요!');
공유 문구들은 여전히 고민되네요...(0개국어 한사람 더 추가요)

2024-06-07 07:49 UTC, mdgarden commented on app/kits/new/components/NewKitForm/index.tsx
> +        {id ? 'close' : 'open'} modal
여기도 단순히 toggle modal 로 변경해도 괜찮을 것 같습니다. (버튼에 대한 동작은 모달의 표시 상태 전환으로 알 수 있으므로)

2024-06-07 07:57 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +        𝕏
[Blackboard Bold](https://en.wikipedia.org/wiki/Blackboard_bold)라는 폰트로 유니코드에 존재하기 때문에 항상 같은 표시가 보장됩니다.

2024-06-07 08:01 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +  const [id, setId] = useState<string>('');
링크 공유 시 `id` 가 사용됩니다. `getTwitterShareLink`, `copyToClipboard` 를 참고해주세요.

2024-06-07 08:12 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +export default function SuccessModal({ id }: { id: string }) {
[React 공식 문서](https://react.dev/learn/choosing-the-state-structure#principles-for-structuring-state)에서는 `Group related state. If you always update two or more state variables at the same time, consider merging them into a single state variable.` 동시에 자주 업데이트 되는 상태는 하나로 묶어 사용하는 것을 추천합니다. `SuccessModal`의 가시성은 `id`의 유무에 의존하므로 `id` 하나로 사용하는 것이 낫다고 생각합니다.

2024-06-07 08:18 UTC, 2chanhaeng commented on lib/constants.ts
> +export const AUTO_TWEET = encodeURI('제가 만든 키트로 릴레이를 시작해보세요!');
로컬 팀원 급구@@@@@@
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/8592d04c-dcf6-4662-a203-9fb9e855bea7)

2024-06-08 07:51 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +export default function SuccessModal({ id }: { id: string }) {
공유해주신 공식 문서의 내용과 지금 제가 드린 의견이 같은 내용인 것 같지는 않은데...개인적으로는 `visible`프롭이 안들어가는 모달은 본 적이 없는 것 같습니다. 희님께 결정권 토스하겠습니다. @blissful-y0

2024-06-11 06:55 UTC, 2chanhaeng reviewed
`Modal` 컴포넌트를 재사용할 수 있도록 분리했습니다.

2024-06-11 06:55 UTC, 2chanhaeng commented on components/Modal/index.tsx
> +}
추후 재사용 가능하도록 `Modal` 컴포넌트를 분리했습니다.

2024-06-11 06:55 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +);
테스트용 버튼도 코드 상 보기 안 좋아서 분리 했습니다.

2024-06-11 06:55 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +  const isModalOpen = !!kitId;
모달 열린 상태를 위한 변수를 추가했습니다.

2024-06-11 06:55 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +}
`Modal` 컴포넌트를 사용해 내부만 구현하면 되도록 분리했습니다.

2024-06-11 07:06 UTC, 2chanhaeng commented on app/layout.tsx
> +        <header className="border-b px-4 py-2 w-full top-0 sticky bg-background z-40">
테스트 중 버그를 발견해서 수정했습니다.
- 수정 전
  ![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/0319fd04-8a90-4c1b-b2ce-9ad8c492c643)
- 수정 후
  ![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/3770900c-d870-4a81-9d11-09bf59481fb0)

2024-06-12 02:44 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +export default function SuccessModal({ id }: { id: string }) {
추후 재사용을 위해 [모달](https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/122/files/66f195ec185f78f60e68f0c6a12f364260b3da93#diff-6c76932ee6fb8e6697060ffe8a162f2a22f4c4246ab9dcea18164e0a2b20497d) 컴포넌트를 분리하면서 `open` 이라는 prop을 추가했고 해당 페이지에서는 `id`가 `thruthy`인지 `falsy`인지를 통해 계산되는`isModalOpen` 이라는 변수를 할당해 모달의 `open` prop 으로 전달했습니다.

2024-06-12 02:47 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +        {id ? 'close' : 'open'} modal
반영했습니다! f7bb2b329e64a59e018ee9f75411f81ff8116a4a

2024-06-13 12:56 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +export default function SuccessModal({ id }: { id: string }) {
모달의 표시 여부를 `visible`로 표기하는 것은 일반적인 관례인 것으로 알고 있습니다. (타입 파일/컴포넌트 파일을 대문자로 표기하고 보조적인 파일들을 모아놓은 폴더 이름이 `util`혹은`lib`로 고정이듯)
[네이티브 링크이긴한데 여기서도 visible로 표시하고 있습니다.](https://reactnative.dev/docs/modal)

2024-06-14 12:52 UTC, mdgarden reviewed
다음 내용 수정 검토 부탁드립니다
- 주석에 적절한 앵커 추가
- 링크 복사 버튼 클릭 시 alert 으로 복사 완료 문구 표시

상기 내용 검토 및 수정 후 꼭! 테스트용으로 작성하신 모달 버튼들 삭제하시고 머지부탁드립니다!

2024-06-14 12:52 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +        {/* 키트 페이지로 이동 */}
저도 저번에 희님이 알려주셔서 알았는데, 주석에 명확하게 단서를 붙이는 것(ex. TODO)를 앵커라고 하는 것 같습니다. TODO나 NOTE라고 붙이면 vscode에서 추적이 가능하니 용도에 맞게 붙여주시면 좋을 것 같아요. 
저는 TODO만 하이라이트 해주는 확장프로그램 쓰고 있었는데 찾아보니 vscode 에 anchor라는 확장프로그램이 있어서 그걸로 갈아탔습니다!

2024-06-14 12:52 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +        {/* 키트 페이지로 이동 */}
https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/79#discussion_r1618438828
^ 희님 코멘트

2024-06-14 12:52 UTC, mdgarden commented on app/kits/new/components/NewKitForm/index.tsx
> +      {/* TODO: 배포 시 제거 */}
이 내용들은 리뷰 완료 후, 머지 전에 꼭 삭제 부탁드립니다!

2024-06-14 12:52 UTC, mdgarden commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +      <button onClick={copyToClipboard(path)} className={styles.button}>
alert으로 "키트 주소가 클립보드에 복사되었습니다!" 같은 문구를 표시해주면 좋을 것 같아요!

2024-06-14 12:52 UTC, mdgarden commented on app/kits/new/components/NewKitForm/index.tsx
> +  const form = useForm<FormValues>({ resolver: zodResolver(FormSchema) });
질문) 좀 늦은 질문인데, 저번에 희님과 zod인지 yup인지 얘기가 잠깐 나왔었던 것 같은데 혹시 희님과 따로 이야기가 진행되신게 있으신가요?

2024-06-15 04:02 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +  const form = useForm<FormValues>({ resolver: zodResolver(FormSchema) });
따로 대화 나눈건 없고 일단 zod 로 진행하고 있었습니다.

2024-06-15 04:32 UTC, 2chanhaeng reviewed
마당님의 리뷰를 반영했습니다!

2024-06-15 04:32 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +      <button onClick={copyToClipboard(path)} className={styles.button}>
반영했습니다! e6605b369edf83a050f78894120f26dd6b8eac72

2024-06-15 04:32 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/SuccessModal.tsx
> +        {/* 키트 페이지로 이동 */}
반영했습니다! 85e8e091cc17c78799ff2f168adc674242886699

2024-06-15 04:32 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/index.tsx
> +      {/* TODO: 배포 시 제거 */}
반영했습니다! f611723523d9bbe1cd9eb66b7f93757847debedc

2024-06-15 04:32 UTC, 2chanhaeng commented on components/Modal/lib.ts
> +const toastCopied = () => toast('링크가 복사되었습니다!');
`toast` 를 발생시키는 함수입니다.
![링크가 복사됐음을 알리는 토스트](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/dc81a0ff-48e1-4cad-80fa-c96e861f18a4)

2024-06-15 04:32 UTC, 2chanhaeng commented on components/Modal/lib.ts
> +};
링크 복사 버튼을 누르는 이벤트를 관리하는 핸들러입니다.

2024-06-15 04:32 UTC, 2chanhaeng commented on components/ui/sonner.tsx
사용자에게 간단한 알림을 보낼 수 있는 `toast` 함수와 이를 보내기 위한 `Toaster` 컴포넌트입니다.
자세한 설명은 [공식 문서](https://ui.shadcn.com/docs/components/sonner)를 참고해주세요.

2024-06-15 04:32 UTC, merged