#43 키트 생성 태그 입력 필드
ZZIPSA/kkuk-kkuk-fe pull request #130
Opened 2024-06-12 03:38 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #43 
키트 생성 폼의 태그 입력 필드를 완성했습니다.

https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/c1245c8e-149b-4f16-a9ec-4452001eb9d7

## 테스트 내용

- 태그는 다음과 같은 조건을 만족하면 입력 가능합니다.
  - 두 글자 이상입니다.
  - 열 글자 이하입니다.
  - 공백을 포함하지 않습니다.
  - 중복되지 않아야 합니다.
- 해당 조건을 하나라도 불만족할 경우 입력이 불가능합니다.
- 태그는 중복되지 않는 여러 태그를 입력할 수 있습니다.
- 태그가 넘치면 좌우로 스크롤해서 가려진 태그를 볼 수 있습니다.
- 태그 우측의 X 버튼을 누르면 태그를 제거할 수 있습니다.

### 리뷰어에게
#### 리뷰하기 전

**#128, #121 머지 이후 리뷰 바랍니다.**
`app/kits/new/components/NewKitForm/Tags.tsx` 를 위주로 봐주시기 바랍니다.

#### 리뷰 후

### 체크리스트

- [ ] 리뷰하는데 20분 이상 필요한가요? _20분 초과할 경우, 예상 리뷰 시간을 덧붙여주세요_
- [ ] 셀프 리뷰를 진행했습니다.
- [x] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [x] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-06-12 04:43 UTC, 2chanhaeng reviewed
`app/kits/new/components/NewKitForm/Tags.tsx` 와 관련된 코드 위주로 리뷰해주시면 감사하겠습니다.

2024-06-12 04:43 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/lib.ts
> +    if (input.validity.valid === false) return e.currentTarget.reportValidity();
입력값이 유효하지 않은 경우입니다.

2024-06-12 04:43 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/schema.ts
> +    .array(),
`useFieldArray`는 flat array 를 처리하지 못한다고 해서 zod 스키마를 변경했습니다.

2024-06-12 04:43 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/lib.ts
> +};
`Tags` 내 `input` 에 태그를 입력 시에 발생하는 이벤트의 핸들러 입니다.

2024-06-12 04:43 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/lib.ts
> +    if (input.validity.valid === false) return e.currentTarget.reportValidity();
태그가 유효한지 확인 후 유효하지 않은 경우 검사 결과를 사용자에게 보여주는 과정입니다.

2024-06-12 04:43 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/lib.ts
> +    input.value = ''; // 입력된 값 초기화
유효한 값이 입력된 경우 필드에 해당 값을 추가하고 `input`을 초기화 합니다.

2024-06-14 01:24 UTC, blissful-y0 commented on app/kits/new/components/NewKitForm/index.tsx
배포 시 제거해야 하는 것들은 주석처리 해서 PR 다시 올려주세요!

2024-06-14 13:08 UTC, mdgarden requested changes
레이아웃에 수정사항이 있습니다! 확인 후 수정 부탁드립니다

2024-06-14 13:08 UTC, mdgarden commented on app/kits/new/components/NewKitForm/schema.ts
> +  tags: z
화면상 태그 입력이 필수로 설정되어 있습니다. zod와 입력 레이아웃에서 필수로 설정되어있는 부분이 있다면 확인 후 수정 부탁드립니다.
<img width="791" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/66259746/415e1aee-8e3d-4a38-8ae1-97de4406986f">

2024-06-15 15:03 UTC, merged