#136 #137 #138 #139 해결
ZZIPSA/kkuk-kkuk-fe pull request #140
Opened 2024-06-13 10:28 UTC by 2chanhaeng

## 작업 내용

**#129 완료 후 리뷰 부탁드립니다.**
관련 이슈:
  - #136 
    [변경 내역](https://github.com/ZZIPSA/kkuk-kkuk-fe/compare/f176a2ac57b699e949471f769e01800205f4900f..0ae38094f71ed4eae7cfe56d44025e036fedc24a)
  - #137 
    [변경 내역](https://github.com/ZZIPSA/kkuk-kkuk-fe/compare/cb2dc56728bb2d0fab69cd3c58ce18f45ea4e60c..dec4ae83cbcccfe26e0d98783909fb5ec76ad05d)
  - #138 
    [변경 내역](https://github.com/ZZIPSA/kkuk-kkuk-fe/compare/dec4ae83cbcccfe26e0d98783909fb5ec76ad05d..412710190c3fba867a30cb3c52dfa8a594993064)
  - #139 
    [변경 내역](https://github.com/ZZIPSA/kkuk-kkuk-fe/compare/0ae38094f71ed4eae7cfe56d44025e036fedc24a..cb2dc56728bb2d0fab69cd3c58ce18f45ea4e60c)

대부분 많은 변경이 필요 없어 하나의 브랜치로 처리했습니다.

## 테스트 내용
- #136 
  `/my` 에 접속합니다.
- #137 
  모달의 문구와 버튼을 변경했습니다.
- #138 
  `snake-3` 스타일 클래스를 추가하여 적용했습니다.
- #139 
  `Submit` 컴포넌트를 생성하여 적용했습니다.

### 리뷰어에게

**#129 완료 후 리뷰 부탁드립니다.**

### 체크리스트

- [ ] 리뷰하는데 20분 이상 필요한가요? _20분 초과할 경우, 예상 리뷰 시간을 덧붙여주세요_
- [ ] 셀프 리뷰를 진행했습니다.
- [x] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [x] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-06-14 05:42 UTC, 2chanhaeng reviewed
관련 코드에 대한 리팩토링도 진행했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/[id]/start/components/RallyStartForm/Submit.tsx
> +}
새로 작성한 `components/Submit` 를 이용해 만든 랠리 시작 폼 제출 버튼입니다.
- 필수 항목 입력 전
  ![필수 항목 입력 전](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/91581ea9-5e33-4f36-b061-4e80ba74712b)
- 필수 항목 입력 후
  ![필수 항목 입력 전](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/2174b2b0-8fcd-4be2-9645-f070acdb2e56)

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/[id]/start/components/RallyStartForm/index.tsx
>    );
새로 정의한 `Submit` 버튼을 추가하며 랠리 시작 폼 관련 파일들을 리팩토링 했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/new/components/NewKitForm/Submit.tsx
> +}
키트 생성 폼의 제출 버튼도 `components/Submit` 를 사용해 만들었습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/globals.css
> +}
랠리 미리보기 등을 위한 `snake-3` 스타일 클래스입니다. 해당 클래스를 적용하면 자식이 다음과 같은 순서로 보이게 됩니다.
```
1 2 3
6 5 4
```
- 적용 전
  ![snake-3 적용 전](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/dc24a443-05f5-44f3-86a5-711981cf46ef)
- 적용 후
  ![snake-3 적용 후](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/591d957c-8cbd-49ee-87b3-2a51c650e3ae)

2024-06-14 05:42 UTC, 2chanhaeng commented on components/RallyStamp/index.tsx
> +    <div className={styles.container}>
`snake-3` 클래스를 적용하면 `order` 를 매번 계산하고 지정할 필요가 없어지기 때문에 제거했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/rallies/[id]/components/styles.ts
> +  stamps: 'bg-rally-route bg-contain bg-center bg-no-repeat gap-y-6 gap-x-2 snake-3',
`RallyStamps` 에 `snake-3` 클래스를 적용했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/rallies/[id]/components/RallyStamps.tsx
> +          <RallyStamp key={id} id={id} objectKey={objectKey} status={status} kind={kind} owned={owned} />
`RallyStamps` 에 `snake-3` 클래스를 적용해 `order` prop 이 필요 없어져 제거했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/[id]/components/RallyPreview/index.tsx
> +  stamps: 'bg-rally-route bg-contain bg-center bg-no-repeat gap-y-6 gap-x-2 snake-3',
`RallyPreview` 에 `snake-3` 클래스를 적용했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/[id]/components/RallyPreview/index.tsx
> +              <RallyStamp key={id} id={id} objectKey={objectKey} status={status} kind={kind} owned={owned} />
`RallyPreview` 에 `snake-3` 클래스를 적용해 `order` prop 이 필요 없어져 제거했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/[id]/components/RallyPreview/index.tsx
> +              kind: i === length - 1 ? StampKind.reward : StampKind.default,
추후 스탬프 개수가 가변이 되었을 때를 대비해 변경했습니다.

2024-06-14 05:42 UTC, 2chanhaeng commented on app/kits/[id]/components/StampsPreview/index.tsx
> +            {index === length - 1 && <Gift className={styles.gift} />}
마지막 스탬프에 선물 아이콘을 추가했습니다.
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/7a39975d-67ad-4243-af05-b6026efa3e2c)

2024-06-14 05:42 UTC, 2chanhaeng commented on app/my/settings/@modal/(.)delete-account/page.tsx
> +      {/* 회원 탈퇴시 참여했던 랠리 및<br /> 세트 목록은 복구 불가능해요! */}
준비 중인 기능이라는 안내 문구로 변경했습니다.
이후 기능 완성 후 다시 문구를 복구할 수 있도록 주석처리만 해놨습니다.
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/67d463af-81ab-47e0-8fd9-5cd298b75c16)

2024-06-14 05:42 UTC, 2chanhaeng commented on app/my/settings/@modal/(.)delete-account/page.tsx
> +        .filter(({ key }) => key !== 'delete') // TODO: 기능 완성 후 delete 버튼 활성화(해당 줄 제거)
`filter` 메소드로 탈퇴 버튼만 제거했습니다.
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/af919404-914c-4755-a837-27294fccd80f)

2024-06-14 05:42 UTC, 2chanhaeng commented on components/Submit/index.tsx
> +}
`react-hook-form` 을 사용하는 폼에서 모두 사용할 수 있는 `Submit` 컴포넌트입니다. 폼의 입력값이 유효하지 않거나 이미 제출 중인 경우 비활성화됩니다.

2024-06-15 03:54 UTC, mdgarden requested changes
몇가지 확인 사항이 있습니다 확인 후 수정 부탁드립니다!

2024-06-15 03:54 UTC, mdgarden commented on app/kits/[id]/components/StampsPreview/index.tsx
> +            {index === length - 1 && <Gift className={styles.gift} />}
스탬프 목록의 리워드 이미지에서도 랠리 미리보기와 똑같이 흰색 레이아웃이 하나 들어가야할 것 같습니다

2024-06-15 03:54 UTC, mdgarden commented on app/kits/[id]/start/components/RallyStartForm/index.tsx
>    );
SubmitButton으로 컴포넌트 명을 명확하게 하면 더 좋을 것 같습니다!

2024-06-15 03:54 UTC, mdgarden commented on app/my/settings/@modal/(.)delete-account/page.tsx
> +        .filter(({ key }) => key !== 'delete') // TODO: 기능 완성 후 delete 버튼 활성화(해당 줄 제거)
탈퇴버튼 남기기로 했던 것 같은데..!

2024-06-15 04:58 UTC, 2chanhaeng reviewed
마당님 변경 요청사항 모두 반영했습니다!

2024-06-15 04:58 UTC, 2chanhaeng commented on app/kits/[id]/components/StampsPreview/index.tsx
> +            {index === length - 1 && <Gift className={styles.gift} />}
추가했습니다! b5b0da529a089610a7bd4c01fa0e9cee14963e2e
![배경 레이아웃 추가](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/578759ac-96d0-45f6-9c53-e2c9614dae34)

2024-06-15 04:58 UTC, 2chanhaeng commented on app/kits/[id]/start/components/RallyStartForm/index.tsx
>    );
반영했습니다! defe8359545425f9ce8aa8957756199bbf8a67ac

2024-06-15 04:58 UTC, 2chanhaeng commented on app/my/settings/@modal/(.)delete-account/page.tsx
> +        .filter(({ key }) => key !== 'delete') // TODO: 기능 완성 후 delete 버튼 활성화(해당 줄 제거)
반영했습니다! 31f3948435b62c0ae5d682493c4a688f04880f29
![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/13e4b46c-490e-40ea-b067-271441f614a8)

2024-06-15 13:47 UTC, blissful-y0 approved these changes
LGTM

2024-06-15 14:49 UTC, merged