#8 전체 Kit 조회 페이지 `/kits` 뷰 완성
ZZIPSA/kkuk-kkuk-fe pull request #17
Opened 2024-05-14 08:01 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #8 

전체 Kit 조회 페이지 `/kits` 뷰 완성

![image](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/71a3f6eb-fab2-43cc-91a3-b446a34154b6)

## 테스트 내용

- 페이지를 스크롤 할 수 있습니다.
- 태그리스트를 스크롤할 수 있습니다.

### 리뷰어에게

MVP 를 참조해주세요.

### 체크리스트

- [x] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
  - 이슈와 관련 없는 일부 커밋을 컨벤션에 맞게 작성하지 않았습니다. 다음부터 신경쓰도록 하겠습니다.
- [x] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-05-14 16:47 UTC, 2chanhaeng commented on app/kits/page.tsx
> +      {kits.map(({ id, title, description, thumbnailImage, tags, uploader }) => (
수정했습니다. e6a24644070c1ed243a50656d2ad5a7c94d9b390

2024-05-14 16:57 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +            className="border-black/20 border rounded-md aspect-square w-full h-full object-cover"
저도 그러고 싶은데 일반적인 문자열로 작성하면 tailwind 익스텐션이 인식을 못해서 난이도가 너무 올라갑니다ㅠㅠ 혹시 일반 문자열로 작성해서 tailwind 익스텐션이 인식하도록 적용하는 방법이 있을까요?

2024-05-14 17:44 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +          <AvatarImage src={thumbnailImage} />
수정했습니다! b2f692e63aeec19a2bf95606103e8f27aa9074d6

2024-05-14 17:46 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +export default function KitCard({ id, title, thumbnailImage, tags, uploader: { nickname }, className, ...props }: KitCardProps) {
전자의 경우 인터페이스를 이용해 prop을 명시해 수정했습니다! 63ddccad5ba7bb7bc7101bf15f4b1ea06dfef755

2024-05-14 17:47 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +export default function KitCard({ id, title, thumbnailImage, tags, uploader: { nickname }, className, ...props }: KitCardProps) {
후자의 경우 개인적인 코딩 스타일 차이라고 생각합니다. 별 차이 없고 코드가 더 길어져 오히려 가독성이 더 떨어진다고 느껴져 개인적으로 인자에서 직접 구조 분해를 하는 것을 선호합니다.

2024-05-15 09:57 UTC, blissful-y0 commented on app/kits/components/KitCard.tsx
> +            className="border-black/20 border rounded-md aspect-square w-full h-full object-cover"
익스텐션을 사용하지 않아서 말씀 드리기가 어려운데 혹시 작성 완료하고 이후에 따로 상수로 빼는 방식도 작동을 안하는걸까요?

2024-05-15 10:00 UTC, blissful-y0 commented on app/kits/components/KitCard.tsx
> +export default function KitCard({ id, title, thumbnailImage, tags, uploader: { nickname }, className, ...props }: KitCardProps) {
어플리케이션의 사이즈가 커질수록 복잡도가 높아지고, 많은 컴포넌트/데이터를 활용하게 되는데 이럴 경우 유지보수와 확장성을 고려했을 때 props를 descturcre 하는 방식이 좀 더 많이 사용되는거같습니다 (함수 파라미터 목록을 수정할 필요가 없음)
airbnb나 material ui에서는 제안드린 방식으로 코드 작성하는 것으로 알고 있습니다

2024-05-15 10:26 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +export default function KitCard({ id, title, thumbnailImage, tags, uploader: { nickname }, className, ...props }: KitCardProps) {
현재 저희가 사용하는 Next.js 의 [소스 코드](https://github.com/vercel/next.js/blob/0b261f0919c82c8b6f1ff08c10657ba9f57123ba/packages/next/src/client/portal/index.tsx#L9) 혹은 [공식 문서](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#slots) 에서는 인자에서 직접 분해하는 방식을 사용합니다. 

<img width="536" alt="Next.js 소스 코드의 일부" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/b650f299-7e2e-4972-bcb8-6d9e61e93ea2">

![Parallel Routes 의 예제 코드 중 일부](https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/146dae54-53e4-4544-9a9a-3e2c529696c9)

2024-05-15 11:46 UTC, mdgarden requested changes
main 반영 부탁드립니다.

2024-05-15 11:46 UTC, mdgarden commented on .eslintrc.json
> +  "env": {
PR 작성시에는 항상 최신 main을 반영하여 리뷰해야하는 파일만 볼 수 있도록 해주세요.

2024-05-15 11:46 UTC, mdgarden commented on app/kits/components/KitCard.tsx
> +interface KitCardProps extends Pick<Kit, KitKeys>, React.ComponentPropsWithoutRef<typeof Card> {
희님과의 리뷰 코멘트를 확인하니 기존 코드는 type이었던 것 같은데, interface로 바꾸신건가요?
나중에 다시 이야기하더라도 우선은 interface로 바꾸신 이유를 이슈나 PR에 코멘트로 남겨주세요.

2024-05-15 11:49 UTC, mdgarden commented
추가) resolve되어서 여기에 덧붙입니다.
저도 업무에서 희님 방식으로 사용했었습니다.

2024-05-15 14:02 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +interface KitCardProps extends Pick<Kit, KitKeys>, React.ComponentPropsWithoutRef<typeof Card> {
오류를 줄이기 위해 기존에 있던 타입으로부터 extends 해서 정의하기 위해 `interface`를 사용했습니다.

2024-05-15 15:23 UTC, mdgarden approved these changes

2024-05-15 15:23 UTC, mdgarden commented on app/kits/components/KitCard.tsx
> +interface KitCardProps extends Pick<Kit, KitKeys>, React.ComponentPropsWithoutRef<typeof Card> {
같은 내용을 type으로 바꿔쓸 수 있을 것 같기도한데...🧐 우선은 이런 내용이 있었다 정도로만 기록해두겠습니다.

2024-05-15 15:23 UTC, merged