#168 랠리 기한 컴포넌트 추가 및 #183 해결
ZZIPSA/kkuk-kkuk-fe pull request #184
Opened 2024-07-01 09:06 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #168 #183
랠리 기한 컴포넌트를 추가했습니다.
스탬프 버튼이 눌리지 않는 버그를 수정했습니다.

## 테스트 내용

https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/8a643768-5478-44cf-9056-299d6ef890cf

#168 
- [ ] 진행 중인 랠리에 기한을 나타내는 깃발 모양 아이콘이 나타납니다
- [ ] 완료된 랠리에만 완료일이 나타납니다.
#183
- [ ] 진행 중인 랠리의 버튼이 활성화됩니다.

### 리뷰어에게
#### 리뷰하기 전

유틸리티 패키지를 설치했습니다. 실행 전 패키지 설치 후 정상적으로 실행 가능합니다.

#### 리뷰 후

### 체크리스트

- [ ] 리뷰하는데 20분 이상 필요한가요? _20분 초과할 경우, 예상 리뷰 시간을 덧붙여주세요_
- [ ] 셀프 리뷰를 진행했습니다.
- [x] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [x] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-07-01 09:33 UTC, 2chanhaeng reviewed
유틸리티 용으로 `fx-ts` 라는 패키지를 설치했습니다. 해당 패키지에 대해서는 [공식 문서](https://fxts.dev/)를 참고하실 수 있습니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/components/lib.ts
> +    : StampStatus.uncheckable; // 아니면 다음에 찍을 스탬프
#183 관련 로직 오류가 있어 수정했습니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +  );
API 에 랠리 데이터를 요청해서 응답 받은 데이터를 파싱하고 에러를 처리하는 함수입니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +});
랠리 데이터를 파싱하는 하는 함수입니다.
날짜값들은 문자열로 받아와지기 때문에 `Date` 로 형변환을 해줬습니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +  );
날짜 관련 값들을 문자열로 파싱하는 함수입니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/page.tsx
> +  // TODO - get stampable from api
API 에서 받아와야할 더미 값들입니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on app/api/rallies/[id]/route.ts
> +  }
큰 변경은 없고 타입 명시와 추후 에러 핸들링하기 편하도록 약간의 변경을 줬습니다.

2024-07-01 09:33 UTC, 2chanhaeng commented on lib/either.ts
> +export type Either<L, R> = Left<L> | Right<R>;
예외 처리용 타입입니다. [관련 문서](https://gcanti.github.io/fp-ts/modules/Either.ts.html)

2024-07-01 09:33 UTC, 2chanhaeng commented on lib/utils.ts
> +    set(key)(fn(obj))(obj);
유틸리티를 몇개 구현했습니다. 복잡한 구조의 함수는 없으니 주석만 보셔도 대부분 이해 가능 하실겁니다. 사용 예제는 `app/(back)/rallies/[id]/lib.ts`를 참고 해주세요.

2024-07-01 14:04 UTC, mdgarden commented
```
Type error: Argument of type 'Date | null' is not assignable to parameter of type 'Date'.
  Type 'null' is not assignable to type 'Date'.
  68 |     derive('since')(({ createdAt }) => displayDateYyMmDd(createdAt)),
  69 |     derive('until')(({ isActive, deadline }) => (isActive ? displayDateYyMmDd(deadline) : null)),
> 70 |     derive('completed')(({ isActive, percentage, updatedAt }) => (!isActive && percentage === 100 ? displayDateYyMmDd(updatedAt) : null)),
     |                                                                                                                       ^
  71 |     remain(['dDay', 'since', 'until', 'completed']),
  72 |   );
  73 |
```

에러 로그 남기고 갑니다!

2024-07-01 16:55 UTC, mdgarden commented on app/(back)/rallies/[id]/lib.ts
> +  );
`pipe`는 Next.js에서 자체적으로 제공하는 함수인가요?

2024-07-01 16:56 UTC, mdgarden commented on app/(back)/rallies/[id]/lib.ts
> +});
날짜를 처리하는 과정은 앱 전체에 걸쳐서 사용될 가능성이 높기 때문에 공통 `lib`로 빼서 관리하는게 좋을 것 같습니다!

2024-07-01 16:57 UTC, mdgarden commented on app/(back)/rallies/[id]/lib.ts
> +  );
날짜를 처리하는 과정은 앱 전체에 걸쳐서 사용될 가능성이 높기 때문에 공통 lib로 빼서 관리하는게 좋을 것 같습니다! (API에서는 일관된 DateTime 형식으로 반환하고 있으므로)

2024-07-01 16:57 UTC, mdgarden commented on app/(back)/rallies/[id]/page.tsx
> +  // TODO - get stampable from api
#187 리뷰 후 수정 부탁드립니다!

2024-07-01 17:19 UTC, mdgarden requested changes
코드 확인만 했습니다. 실기 확인은 #187 머지 이후 진행하겠습니다!

2024-07-01 17:19 UTC, mdgarden commented on app/(back)/rallies/[id]/lib.ts
> +    derive('dDay')(({ isActive, deadline, today }) => (isActive ? convertMsToDate(deadline.getTime() - today.getTime()) : null)),
여기서 `dDay`는 남은 일수를 표시하는 변수일까요? 디데이 자체는 `deadline`과 같은 뜻이기 때문에 `dayBefore`나 `remainingDate`...같은건 어떨까요?

2024-07-01 17:19 UTC, mdgarden commented on app/api/rallies/[id]/route.ts
> +  }
프리즈마에서 자체적으로 에러 타입도 제공해주는군여! 나중에 PATCH API 대대적으로 수정이 들어갈 것 같은데 참고해서 작성하겠습니다

2024-07-01 17:19 UTC, mdgarden commented on app/(back)/rallies/[id]/lib.ts
> +import { evolve, join, pipe, prop } from '@fxts/core';
라이브러리를 추가하실 때는 어떤 이유로 라이브러리를 추가했는지, 다른 라이브러리와 비교해서 어떤 점이 좋아서 이 라이브러리를 선택했는지도 함께 적어주시면 좋습니다. 이번에는 해당사항이 없으나 저번에 `yup`이나 `zod` 같이 대체 라이브러리가 많은 경우 검토 단계에서 팀원들과 합의가 필요할 수도 있으므로 미리 말씀해주시면 더 좋습니다!

참고)
https://github.com/ZZIPSA/kkuk-kkuk-fe/issues/50#issuecomment-2132037322

2024-07-01 17:19 UTC, mdgarden commented on types/Rally.ts
> +  updatedAt: Date;
마찬가지로 #187 머지 후 수정 부탁드립니다.

2024-07-01 17:19 UTC, mdgarden commented on app/(back)/rallies/[id]/lib.ts
> +  );
아 밑에서 확인했습니다 스루해주세욥ㅎ;;

2024-07-02 05:21 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +    derive('dDay')(({ isActive, deadline, today }) => (isActive ? convertMsToDate(deadline.getTime() - today.getTime()) : null)),
실제 사용자에게 표시될 때도 D-Day로 표시되는 값이기 때문에 `dDay` 라는 이름을 사용했습니다.
<img width="116" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/30fdbc0e-403b-4743-893c-5d211e9aaa18">

2024-07-02 05:22 UTC, 2chanhaeng commented on app/api/rallies/[id]/route.ts
> +  }
넵. [공식 문서](https://www.prisma.io/docs/orm/reference/error-reference)도 참고해보시면 좋을 듯 합니다.

2024-07-02 05:46 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +import { evolve, join, pipe, prop } from '@fxts/core';
`pipe` 라는 함수가 필요해서 추가하게 되었습니다. 해당 함수는 구현 자체는 간단하지만 TS 의 타입 관련 기능 부족으로 타입을 작성하기가 까다롭습니다. 패키지 내 `pipe` 함수 타입 정의를 보시면 아시겠지만 인자의 개수마다 타입을 작성해줘야 합니다.
<img width="1574" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/fb945378-d934-4b32-ad5d-ab4ffefaa39d">
[해당 함수를 구현한 다른 패키지들도 있었습니다.](https://fxts.dev/docs/function-composition) 처음에는 그 중 fp-ts 라는 라이브러리를 사용할까 생각했었습니다. `pipe` 외에도 이번 PR에서 구현한 `Either` 등의 구현체도 존재했기 때문입니다. 하지만 해당 라이브러리는 러닝 커브가 조금 있어서 팀원 분들에게 필요성을 납득시키기 힘이 들 것 같아 고민 중이었습니다. 그러던 중 현재의 `fx-ts` 라이브러리를 발견해 사용하게 되었습니다.

2024-07-03 15:39 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +const getDeadline = ({ deadline }: HasDeadline) => pipe(deadline, diffDates(now()), convertMsToDate, (e) => (e === 0 ? 'Day' : String(e)));
피그마 변경에 맞춰 적용했습니다.
<img width="497" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/881e0025-64e3-4012-ac1b-0775ed1b86e8">

2024-07-03 15:39 UTC, 2chanhaeng commented on app/api/lib/prisma/selects.ts
> +  isPublic: true,
타입을 위해 #187 에서 추가된 컬럼을 `rallySelect`에 추가했습니다.

2024-07-03 15:39 UTC, 2chanhaeng commented on lib/date.ts
> +export const parseNullableDate = (a: number | string | Date | null) => (a ? parseDate(a) : null);
날짜 관련 함수들을 분리했습니다.

2024-07-03 15:39 UTC, 2chanhaeng commented on types/Rally.ts
> +}
DB에서 요청 받은 `RallyData`와 응답 받은 JSON 내 데이터의 타입 차이를 위해 `FetchRallyData`, `FetchedRallyData` 를 정의했습니다.

2024-07-03 15:39 UTC, 2chanhaeng commented on app/(back)/rallies/[id]/lib.ts
> +  extendedDueDate: parseNullableDate,
해당 값들은 nullable 하기 때문에 따로 처리하는 함수를 만들었습니다.

2024-07-04 06:47 UTC, merged