#169 랠리 생성 페이지 기한 입력 컴포넌트 작성
ZZIPSA/kkuk-kkuk-fe pull request #190
Opened 2024-07-08 10:02 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #169 
랠리 생성 시 기한이 입력됩니다.

## 테스트 내용

- [ ] 랠리 생성 페이지에 기한 입력 컴포넌트가 존재합니다.
  <img width="497" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/605cd6ba-baad-48cc-8c16-818319aeca4b">
- [ ] 기한이 입력되면 입력한 기한이 보입니다.
  - [ ] 기한이 입력되면 기한 제거 버튼이 보입니다.
  <img width="492" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/500a1a37-6f6b-4f98-a509-44ee7673083b">
- [ ] 입력 컴포넌트를 클릭하면 입력 모달이 열립니다.
  <img width="364" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/baeb2359-fc23-4b61-aaa9-492f3a407f07">

### 리뷰어에게
#### 리뷰하기 전
- 실행하기 전 `yarn install` 를 실행해 주세요. `picker` 를 위해 react-mobile-picker 라는 패키지를 설치했습니다. 
- `app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/index.tsx` 를 기준으로 동일한 경로에 있는 파일 위주로 리뷰 부탁드립니다.

### 체크리스트

- [ ] 리뷰하는데 20분 이상 필요한가요? _20분 초과할 경우, 예상 리뷰 시간을 덧붙여주세요_
- [ ] 셀프 리뷰를 진행했습니다.
- [x] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [x] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-07-08 10:14 UTC, 2chanhaeng reviewed
`app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/index.tsx` 와 동일한 경로내에 있는 파일 위주로 리뷰 부탁드립니다.
작동 테스트를 위해 API 를 조금 수정했습니다. 임시로 작성했으니 추후 수정하셔도 됩니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/ModalContent.tsx
> +    </Card>
기한 입력 모달입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/Picker.tsx
> +    </Picker>
기한 입력에 사용될 Picker 입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/index.tsx
> +    />
기한 입력 필드 컴포넌트입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/lib.ts
> +const leMaxDeadline = (today: Date) => (date: Date) => convertMsToDate(diffDates(today)(date)) <= MAX_RALLY_DEADLINE_DAYS;
zod에서 기한 입력을 검사하기 위한 함수입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/lib.ts
> +export const presentDeadline = (date?: Date) => (date === undefined ? '' : pipe(dateToArray(date), map(pad02), join(' - ')) + ' 까지');
입력된 기한의 포맷에 맞춰서 표기하기 위한 함수입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/lib.ts
> +export const inputDeadline = (date?: Date) => (date === undefined ? '' : pipe(dateToArray(date), join('-')));
실제 기한이 저장되는 `input` 컴포넌트에 값을 저장하기 위한 함수입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/lib.ts
> +    pipe(picker, getSameYearTargetDate(since), addYearIfOlderThan(since));
상태로 기한을 저장하기 위한 함수입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/lib.ts
> +  );
기한에 필요한 값들을 저장하기 위한 함수입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/lib.ts
> +  pipe(unSynced, E.lift(isDuringUpdated(prev)), E.match(updateMonthDate(since), updateDuring(since)));
기한을 정할 때 일수로 정하는 경우 이에 해당하는 날짜를, 날짜로 정하는 경우 이에 해당하는 일수를 구해 동기화하는 함수입니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on app/api/rallies/route.ts
> +        dueDate,
테스트 용으로 API가 작동하도록 임시로 수정해놨습니다.
추후 필요하신 대로 수정하시면 됩니다.

2024-07-08 10:14 UTC, 2chanhaeng commented on lib/constants.ts
> +export const MAX_RALLY_DEADLINE_DAYS = 100;
랠리 기한을 설정하기 위한 최소 일수, 최대 일수 입니다.

2024-07-08 10:31 UTC, mdgarden requested changes
디데이 관련해서 동작하지 않는 부분이 있었습니다. 확인 부탁드려욥

2024-07-08 10:31 UTC, mdgarden commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/ModalContent.tsx
> +        <CardDescription className="text-left">완주 기한까지 완주하지 못하면 랠리를 더 이상 진행할 수 없습니다.</CardDescription>
먼가.. 이렇게 보니까 "완주"라는 단어가 많이 보여서 어색해보이네요 
"설정한 기한까지 완주하지 못하면 랠리를 더 이상 진행할 수 없습니다."는 어떨까요?

2024-07-08 10:31 UTC, mdgarden commented on app/api/rallies/route.ts
> +        dueDate,
실기 화면에서 기한을 설정한 랠리의 경우, 스탬프를 찍어도 남은 디데이가 갱신되지않았습니다. 확인 후 수정부탁드립니다!

2024-07-09 04:32 UTC, 2chanhaeng commented on app/(back)/kits/[id]/start/components/RallyStartForm/DeadlineField/ModalContent.tsx
> +        <CardDescription className="text-left">완주 기한까지 완주하지 못하면 랠리를 더 이상 진행할 수 없습니다.</CardDescription>
반영했습니다! 84cc145934064279dea5fde1fbf3e01178e898e8
Figma에 해당 사항 반영될 수 있도록 희님께도 전달 부탁 드립니다.

2024-07-09 04:34 UTC, 2chanhaeng commented on app/api/rallies/route.ts
> +        dueDate,
API 는 임시로만 작성한 부분이기 때문에 별도 이슈로 분리해서 작업하는 것이 좋을 것 같습니다.

2024-07-09 10:57 UTC, merged