#38 notFound* 를 default* 로 변경
ZZIPSA/kkuk-kkuk-fe pull request #39
Opened 2024-05-19 07:37 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #38
해당하는 사용자를 찾을 수 없는 경우 표출되는 상수들의 이름을 notFound* 에서 default* 로 변경합니다.

## 테스트 내용

단순 변수명 및 파일명 변경이므로 테스트가 필요하지 않습니다.

### 리뷰어에게

해당 파일을 참조하는 파일이 모두 잘 변경되었는지 확인해주시면 감사하겠습니다.

### 체크리스트

- [ ] 셀프 리뷰를 진행했습니다.
- [ ] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [ ] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-05-19 08:38 UTC, mdgarden commented
리뷰에 앞서 먼저 공통 인식을 정확하게 해야할 것 같습니다.

- 유저를 찾을 수 없는 경우
- 유저가 기본 정보를 설정해놓지 않은 경우
- 유저가 탈퇴한 경우

이 세가지의 케이스는 분명하게 구분되어야합니다.

유저를 찾을 수 없는 경우, 이는 명백하게 에러이므로 에러페이지 혹은 에러 메세지를 표시해야합니다.
유저의 탈퇴로 인해 유저 정보를 조회할 수 없는 경우, 외부적으로는 디폴트값이 표시되더라도 내부적으로는 탈퇴한 유저인지 아닌지 알 수 있어야합니다.

2024-05-19 08:55 UTC, mdgarden requested changes
코드 개선이라는 부분에서 수정할 요소가 많은 것 같습니다. 수정을 진행해주시되, 혹 이전 PR #32  과 겹치는 부분이 있다면 이전 PR을 먼저 머지해주세요.

2024-05-19 08:55 UTC, mdgarden commented on lib/defaults.ts
> +export const defaultUserNickname = '찾을 수 없는 사용자';
변수명은 `default`인데, 메세지는 에러 내용을 담고 있습니다.

닉네임을 설정하지 않은 유저의 기본 닉네임이라면 "꾹꾹이" 등의 다른 명칭을 사용해야합니다.
찾을 수 없는 사용자를 표시해야한다면 이는 컴포넌트 내부에서 표시하는 것이 아닌 다른 에러 처리 방법으로 고민해야할 것 같습니다.

2024-05-19 08:55 UTC, mdgarden commented on lib/defaults.ts
> +export const defaultImage = '/icon';
- `defaultImage`는 너무 포괄적인 명칭입니다. `defaultAvatarImage`등으로 어떤 요소의 기본 이미지인지 조금 더 명확하게 변수명을 변경했으면 좋겠습니다.
- `/icon`이 페이지는 어떤 아이콘을 표시하고 있는 페이지인가요? 코드와 파일명 만으로 알기 어려운 것 같습니다.
- `libs/icons`에 있는 요소들과 같이, 내부에 있는 이미지, 아이콘 소스 등은 변수로 관리해야합니다. 예를 들어,
```ts
// app/lib.tsx

export const getSignedNavBarItems = ({ profileImage }: { profileImage: string | null }): NavBarItemProps[] => [
  { href: '/kits/new', Inner: <Pencil className="h-8 w-8 fill-foreground" /> },
  { href: '/rallies', Inner: <Stamp className="h-8 w-8 stroke-foreground" /> },
  {
    href: '/my',
    Inner: (
      <Avatar className="w-8 h-8 border">
        <AvatarImage src={profileImage ?? '/default-profile.svg'} />
      </Avatar>
    ),
  },
];

```
상기의 코드는

```ts
//... 생략
        <AvatarImage src={profileImage ?? DEAFULT_PROFILE} />
```
이렇게 작성하는 것이 좋습니다.
- 또한 이 파일에 있는 내용들은 상수로 관리하는 것이 적절한 것 같습니다.

```ts
// libs/defaults.ts 파일을
// libs/consts.ts 파일로 이름 변경

export const DEFAULT_NAME = '꾹꾹이';
export const DEFAULT_AVATAR_IMAGE = '...내부 파일 경로.svg';
```
향후 상수가 많아지면 그 때 파일을 분리해도 될 것 같습니다.
- `lib/icons.tsx` 에 있는 아이콘 이름들도 다음과 같이 변경하는 것을 검토해주세요.
```ts
export { default as PENCIL_ICON } from '@/public/pencil.svg';
export { default as STAMP_ICON } from '@/public/stamp.svg';
```

2024-05-19 09:09 UTC, 2chanhaeng commented
해당 상수는 Kit 전체 조회 페이지에서 사용자에게 표출하기 위한 것만을 상정하고 만들어졌습니다. 

> 유저를 찾을 수 없는 경우, 이는 명백하게 에러이므로 에러페이지 혹은 에러 메세지를 표시해야합니다. 

에러 페이지 혹은 에러 메세지는 키트 전체 조회 페이지에서 고려할 사항은 아닌 것 같습니다. 키트 전체 조회 페이지에서 일부 키트의 정보 중 일부인 작성자가 조회되지 않는다고 에러 메세지를 표시하는 것은 사용자에게 불편함을 초래할 것입니다. (물론 내부적으로 로그를 남겨놓을 필요는 있다고 생각합니다.) 이 같은 경우는 아마 특정 사용자 조회 페이지에서 필요할 것 같습니다. 하지만 해당 페이지는 현재 MVP에 존재하지 않습니다. 만약 이를 구현하게 된다면 [`@/app/users/not-found.tsx`](https://nextjs.org/docs/app/api-reference/file-conventions/not-found) 로 구현하면 될 것 같습니다.

> 유저의 탈퇴로 인해 유저 정보를 조회할 수 없는 경우, 외부적으로는 디폴트값이 표시되더라도 내부적으로는 탈퇴한 유저인지 아닌지 알 수 있어야합니다.

마찬가지로 사용자에게 표출하기 위한 것을 상정했기 때문에 현재 PR에서 고려할 사항은 아닌 것 같습니다. 사용자가 계정을 삭제한 경우에는 아예 전체 페이지에서 조회 자체가 불가능하도록 만드는 것이 좋다고 생각합니다.

> - 유저가 기본 정보를 설정해놓지 않은 경우

이런 경우는 처음부터 불가능하도록 내부적으로 처리하는 것이 맞다고 생각합니다. `Auth.js` 사용 시 사용자의 `name` 을 OAuth Provider 에서 가져옵니다.

2024-05-19 09:19 UTC, 2chanhaeng commented on lib/defaults.ts
> +export const defaultUserNickname = '찾을 수 없는 사용자';
- 닉네임을 설정하지 않은 사용자
  닉네임을 설정하지 않는 경우를 불가능하게 만들어야 한다고 생각합니다.
- 찾을 수 없는 사용자
  키트 전체 조회 페이지에서 키트의 일부 정보인 사용자 조회가 불가능하다고 키트 자체가 조회 불가능해지면 사용자에게 불편을 초래할 것입니다. 사용자에겐 디폴트 값을 보여주는 것이 좋다고 생각합니다.

2024-05-19 09:33 UTC, 2chanhaeng commented on lib/defaults.ts
> +export const defaultImage = '/icon';
> * `defaultImage`는 너무 포괄적인 명칭입니다. `defaultAvatarImage`등으로 어떤 요소의 기본 이미지인지 조금 더 명확하게 변수명을 변경했으면 좋겠습니다.

동의합니다. 반영하겠습니다.

> * `/icon`이 페이지는 어떤 아이콘을 표시하고 있는 페이지인가요? 코드와 파일명 만으로 알기 어려운 것 같습니다.

[기본 프로필 이미지](https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/32/files#diff-38709008888174ae0791ae667209ed23384a42116e50cf8e6ec7a582ab6737aa) 를 추가하기 전 임시로 작성한 코드였습니다. #32 머지 이후 수정하도록 하겠습니다. 여담으로 `/icon` 는 [`/icon.tsx`](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#generate-icons-using-code-js-ts-tsx)으로 생성되는 이미지입니다.

> - libs/icons에 있는 요소들과 같이, 내부에 있는 이미지, 아이콘 소스 등은 변수로 관리해야합니다.

동의합니다. 다만 #32 관련 내용이므로 해당 PR에서 반영하도록 하겠습니다.

> - 또한 이 파일에 있는 내용들은 상수로 관리하는 것이 적절한 것 같습니다.

동의합니다. 반영하겠습니다.

> - lib/icons.tsx 에 있는 아이콘 이름들도 다음과 같이 변경하는 것을 검토해주세요.

동의합니다. 다만 #32 관련 내용이므로 해당 PR에서 반영하도록 하겠습니다.

2024-05-19 11:06 UTC, mdgarden commented
## 에러 핸들링에 대해서
> 해당 상수는 Kit 전체 조회 페이지에서 작성자의 정보가 모종의 오류로 조회되지 않았을 때 사용자에게 표출하기 것을 상정하고 만들어졌습니다.
> 키트 전체 조회 페이지에서 일부 키트의 정보 중 일부인 작성자가 조회되지 않는다고 에러 메세지를 표시하는 것은 사용자에게 불편함을 초래할 것입니다. 

동의하기 어렵습니다. 어떠한 이유로든 말씀주신 상황은 "키트 작성자의 정보가 정상적으로 취득되지않은" 경우입니다. 이는 명백한 에러입니다. 정말 알 수 없는 어떠한 오류로 API가 200인데 해당 항목만 비워져있을 수도 있고, 아니면 API가 정직하게 오류 코드를 반환했을 수도 있고, 여러 에러 상황이 있을 수 있겠습니다만, 어떠한 이유일지라도 **에러가 발생하면 사용자의 추가적인 행동을 막아야합니다.** 특히 DB와 접속하는 API라면 더더욱 그렇습니다.

말씀 주신 대로 상정해서 생각해도, 일부라고는 하나 어쨌든 키트의 정상적인 정보를 취득하지 못한 상황입니다. 그럼 다른 항목들 역시 정상적으로 취득되었다는 보장이 없습니다. 
만약 정상적으로 취득되었다고 하더라도, 키트의 상세페이지로는 어떻게 넘어갈 것이며, 어찌저찌 키트의 상세페이지로 넘어가서 사용자가 랠리 작성까지 완료해서 "랠리 시작"이라는 버튼을 눌렀을 때 그때서야 에러를 표시한다는 뜻일까요? 또, 작성자의 정보를 모르는채로 키트를 보게 하는 것은 괜찮다는 뜻인가요?
"에러 메세지를 어떻게 표시할 것인가"에 대한 논의는 할 수 있어도, "에러가 있음에도 유저가 계속 사용하게 하는 상황"에는 타협의 여지가 없다고 생각합니다.

말씀 주신 시나리오는 해당 사용자가 탈퇴한 사용자일 때만 성립할 수 있을 것 같습니다.

## 변수명에 대해서

또한, 설령 초무님이 주신대로 에러를 상정한다고 해도 `찾을 수 없는 사용자`라는 명칭은 "디폴트"값이 될 수 없습니다. 에러는 "디폴트"가 아니기 때문입니다.
해당 변수명으로는 `ERROR_USER_NAME`, 혹은 탈퇴한 경우라면 `DELETED_USER_NAME` 등이 있을 것 같습니다.

## 사용자 삭제에 대해서

> 사용자가 계정을 삭제한 경우에는 아예 전체 페이지에서 조회 자체가 불가능하도록 만드는 것이 좋다고 생각합니다.

이 부분에 대해서는 이슈의 범위를 벗어나고, 추가적인 논의가 필요합니다. 업로더가 탈퇴한 경우, 해당 업로더가 올린 키트로 랠리를 진행하고 있는 유저들의 상황을 고려해야합니다.

## 유저의 기본정보에 대해서

> 이런 경우는 처음부터 불가능하도록 내부적으로 처리하는 것이 맞다고 생각합니다. Auth.js 사용 시 사용자의 name 을 OAuth Provider 에서 가져옵니다.

저도 닉네임은 필수 항목으로 관리해야한다는 것에 동의합니다. 또한 필수항목으로 관리된다면 더더욱 `const nickname = uploader?.nickname ?? DEFAULT_USER_NICKNAME;`이 코드는 에러로서 표시해야합니다.

해당 스키마는 수정해놓겠습니다.

2024-05-19 11:11 UTC, mdgarden commented on lib/defaults.ts
> +export const defaultImage = '/icon';
> 그리고 lib/icons.tsx 에서 내보내는 아이콘들은 단순 값이 아니라 컴포넌트입니다. 

해당 파일은 JSX를 반환하고 있지않은데 컴포넌트인가요?

2024-05-19 11:13 UTC, mdgarden commented on lib/defaults.ts
> +export const defaultUserNickname = '찾을 수 없는 사용자';
스키마에서 nickname을 옵셔널로 설정해놓아서 작성하신 코드인줄 알았습니다.
관련된 내용은 코멘트로 작성해두었으니 찬찬히 읽어봐주세요.

2024-05-19 11:23 UTC, 2chanhaeng commented on lib/defaults.ts
> +export const defaultImage = '/icon';
> 해당 파일은 JSX를 반환하고 있지않은데 컴포넌트인가요?

네 #32 관련 내용이라 현재 PR 브랜치에서는 적용되어 있지 않은데 [#32 의 next.config 파일의 `webpack`](https://github.com/ZZIPSA/kkuk-kkuk-fe/blob/8607678ce4448b63c6d02411e1f33fb4625016cb/next.config.mjs#L21) 에서 '@svgr/webpack' 를 추가해 svg 파일을 바로 컴포넌트처럼 사용할 수 있습니다. [예시](https://github.com/ZZIPSA/kkuk-kkuk-fe/blob/8607678ce4448b63c6d02411e1f33fb4625016cb/app/lib.tsx#L20) 참고 바랍니다.

2024-05-19 11:27 UTC, mdgarden commented on lib/defaults.ts
> +export const defaultImage = '/icon';
네 알겠습니다. 컴포넌트라면 컴포넌트 폴더의 하위 파일로 이동을 검토부탁드립니다.

2024-05-19 11:31 UTC, 2chanhaeng commented
마당님께서 해당 이슈 관련해서 중요도를 높게 평가하고 계시고 해당 이슈 관련해서 의견이 확고하시니 마당님께서 직접 이슈를 맡으시는 건 어떠신가요?

2024-05-19 11:36 UTC, mdgarden commented
제가 이슈를 맡는 것은 상관없으나 에러 핸들링에 대한 부분은 분명히 하고 가야한다고 생각합니다. 지금 이 부분에서 초무님과 공감대를 형성하지 못하면 앞으로 100% 같은 부분에서 또 부딪히게 됩니다. 향후 발생하는 다른 코드 개선에 부분에 대해서도 마찬가지입니다.

저는 지금껏 일부분만 에러 처리를 하는 홈페이지를 못본 것 같은데, 혹시 알고 계신 예시가 있다면 제시 부탁드립니다.

그리고 제가 겪은 바로는 원래 코드 개선이 들어가는 부분은 업무에서도 좀 유난이 많습니다...
공통적인 인식과 룰을 만들어가는 부분이니 충돌이 발생하는 것은 당연한 부분이고, 또 그러한 지점을 공격받는다고 생각하지 않으셨으면 좋겠습니다.

2024-05-19 11:37 UTC, 2chanhaeng commented on lib/defaults.ts
> +export const defaultImage = '/icon';
현재 작업중인 브랜치 issue/7 에서 관련 내역을 수정한 게 있어 해당 브랜치에서 수정하겠습니다.

2024-05-19 11:54 UTC, 2chanhaeng commented
#38 과 현재 PR은 변수명에 관한 것이라고 생각합니다. 관련 논의는 새로운 이슈를 생성해주시고 해당 이슈에서 논의하는 것이 좋을 것 같습니다.

2024-05-19 11:57 UTC, mdgarden commented
네, 말씀주신대로 변수명에 대해 설득하기 위해서 논의가 벗어난 것 같습니다.
결과적으로 `찾을 수 없는 사용자`가 디폴트 값이 될 수 없다는 의견에 대해서 동의하기 어렵다는 말씀이시죠?

2024-05-19 12:15 UTC, 2chanhaeng commented
다량의 키트 조회 시 내부적 오류로 인해 키트 작성자가 조회 되지 않는 경우 사용자에게 키트 작성자의 이름 대신 노출되는 값으로 `찾을 수 없는 사용자`가 적절하다고 생각합니다. 그 외의 경우에는 다른 이슈에서 논의하는 것이 적절하다고 생각합니다.

2024-05-19 12:32 UTC, mdgarden commented
질문의 포인트가 맞지 않는 것 같습니다.
- 저는 애초에 `찾을 수 없는 사용자`는 심각한 에러이므로 이 변수 자체가 무효라고 생각하여 위 코멘트에서 에러 핸들링에 대해 말씀드렸습니다. 말씀주신대로 이에 대한 논의는 범위에서 벗어나므로 이 부분은 생략하겠습니다.
- 만약 `찾을 수 없는 사용자`를 꼭 표시해야한다면, `default`가 들어가는 변수 이름이 적절하지 않다고 생각했고, 변수명에 에러로서 명시할 것을 제시했습니다. 
- 또한 예시로서 변수명을 `ERROR_USER_NAME`으로 변경할 것을 제시했습니다. 혹은 에러라는 것이 명시된다면 다른 변수명도 괜찮습니다.

> 다량의 키트 조회 시 내부적 오류로 인해 키트 작성자의 이름을 사용자에게 정강적으로 표출할 수 없는 경우
이 케이스에 대해서 서로 공감대 형성이 못되고 있는 것 같습니다.

그러니까 초무님은 설령 사용자 정보를 찾을 수 없는 것이 에러라고 하더라도 `찾을 수 없는 사용자`라는 메세지는 에러로 보지 않겠다는 말씀인걸로 이해했는데, 제가 이해한게 맞나요?
맞다면 우선 `DEFAULT_USER_NAME`등으로 다른 상수에 맞춰 수정 및 컨플릭트 해결 후 머지 부탁드립니다.
이슈는 제가 별도로 작성해놓겠습니다.

2024-05-19 12:47 UTC, blissful-y0 commented
이슈에 대해 확인했고 회고까지 얼마 남지 않아서 서면이 아니라 이야기로 해결하는 게 좋을 것 같습니다. 일단 유저에 default 개념을 적용하는 거 자체가 존재할 수 없는 경우 아닌가 싶습니다
찾을 수 없는 유저 -> 존재하지 않는 유저 -> 결과론적으로 탈퇴한 유저라고 생각해요 이 경우는 deleted user말고는 다른 케이스가 존재할 수 없을 것 같습니다...

2024-05-19 12:49 UTC, blissful-y0 commented
별개로 default 값이 존재할 수 있는 것은 유니크하지 않은 변수들뿐이라고 생각해요

2024-05-20 03:12 UTC, mdgarden commented
말 번복해서 죄송합니다. 자고 일어나서 다시 생각해도 역시 이 부분은 타협의 부분이 아닌 것 같습니다.
코드는 다음과 같이 수정해주시고, 컨플릭트 해결 부탁드립니다. 제가 위에서 작성한 글 다시 찬찬히 읽어보시고 그래도 납득이 어려운 부분이 있다면 디코로 설명해드리겠습니다.

```ts
//app/kits/components/KitCard.tsx

//...
export default function KitCard({ id, title, thumbnailImage, tags, uploader, className, ...props }: KitCardProps) {
// thumbnailImage ??= DEFAULT_PROFILE; // 이 줄 삭제
//  const nickname = uploader?.nickname ?? DEFAULT_USER_NICKNAME;  // 이 줄 삭제
  const profileImage = uploader?.profileImage ?? DEFAULT_PROFILE;
return (
    <Card className={cn('flex flex-col border-0 shadow-none gap-2', className)} {...props}>
//...
```

```ts
// lib/constants.ts

export const DEFAULT_PROFILE = '/default-profile.svg';
// export const DEFAULT_USER_NICKNAME = '찾을 수 없는 사용자'; // 이 줄 삭제
```

2024-05-20 03:57 UTC, 2chanhaeng commented
null 인 경우 타입 에러만 나지 않도록 처리해뒀습니다. 이것마저 처리하려면 스키마를 수정하셔야 합니다.

2024-05-20 04:03 UTC, mdgarden commented
네 검토 후 수정하겠습니다. 고생하셨습니다

2024-05-20 04:04 UTC, merged