issue/#20 refactor:  타입 정리
ZZIPSA/kkuk-kkuk-fe pull request #46
Opened 2024-05-20 09:09 UTC by mdgarden

## 작업 내용

관련 이슈: #20 
이 프로젝트에서 효율적으로 백엔드 API들을 구현하기 위해 필요한 밑작업들을 확인하고 적용합니다.
확인이 필요했던 항목들 중, 이번 이슈에서는 타입정리만 진행했습니다.
다른 항목들이 이번 이슈에서 제외된 이유는 해당 이슈의 코멘트들을 확인해주세요. 

## 테스트 내용

- [x] 프론트에서 직접적으로 '@prisma/client' 를 사용하지 않게 합니다.
- [x] 모든 모델을 작성하고, 다른 분들이 타입을 유연하게 작성할 수 있도록 예시를 작성합니다.
- [x] 현재 작성되어있는 프론트 페이지에 타입을 적용합니다.

### 리뷰어에게

- 여러가지 논의해야할 곳이 많습니다.
- 제가 이번 타입 정리를 하면서 가장 중요하게 생각한 부분은 "프론트와 프리즈마의 분리" 였습니다.
- 그 외의 점들에 대해서는 많이 의견을 나누면서 정해야할 것 같습니다.

### 체크리스트

- [ ] 셀프 리뷰를 진행했습니다.
- [ ] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [ ] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-05-20 09:23 UTC, mdgarden reviewed
앞으로 프론트 분들이 사용하셔야 하는 타입들이니  **코드 보다는 타입의 생성 방법과 사용법을 중점으로 검토** 부탁드립니다. 또한, 타입 작성 방식에 대한 논의는 환영하지만 `types/models.ts`의 역할은 바꾸지 않는 방향으로 검토해주셨으면 좋겠습니다.
리뷰를 시작하시기 전에, 제가 이 프로젝트에서 백엔드를 어떻게 생각하고 구현하려는지에 대해서 **이 코멘트를 먼저 읽어주시면 좋을 것 같습니다.** 
https://github.com/ZZIPSA/kkuk-kkuk-fe/issues/20#issuecomment-2119113563

2024-05-20 09:23 UTC, mdgarden commented on app/components/NavBar.tsx
> +type DefaultUser = Pick<UserModel, 'profileImage'>; // 테스트용
앞으로 프론트에서 타입을 작성할 때 직접적으로 `import { ** } from '@prisma/client';`를 사용하는 일이 없어야합니다. 구체적인 사용방법은 아래에서 설명하겠습니다.

2024-05-20 09:23 UTC, mdgarden commented on app/kits/components/KitCard.tsx
> +type KitCardProps = KitCardInfo & React.HTMLAttributes<HTMLDivElement>;
리액트 요소가 필요없다면 `type KitCardProps = KitCardInfo` 로 작성합니다. 중복으로 보일 수 있으나, 프롭으로 사용되는 타입과 KitCard에서 필요한 정보가 달라질 수 있으므로 구분해가면서 사용하는 것을 추천드립니다.

2024-05-20 09:23 UTC, mdgarden commented on app/kits/page.tsx
> +async function fetchKits(): Promise<KitCardsInfo> {
테스트를 위해 임시로 적어놓은 fetch 함수입니다. 이 부분은 머지 후 프론트 분들이 작업하시면서 자유롭게 변경하시면 됩니다.

2024-05-20 09:23 UTC, mdgarden commented on app/lib.tsx
> +import { UserModel } from '@/types/models';
프론트에서 `'@prisma/client';`를 사용하고 있는 곳이 없도록 수정했습니다.

2024-05-20 09:23 UTC, mdgarden commented on prisma/schema.prisma
> +  uploaderId     String
이번 타입 수정을 위해 임시로 변경한 스키마입니다. 본격적인 스키마 수정은 #45 에서 진행할 예정입니다.

2024-05-20 09:23 UTC, mdgarden commented on types/Rally.ts
> +type RallyStarter = { starter: Pick<UserModel, 'profileImage' | 'nickname'> };
타입 작성의 예시입니다. 필요하실 때 수정하셔서 사용하시면 됩니다. types 폴더에 있는 하위 파일에서는 `model`에 있는 항목만 편집합니다. 리액트 요소의 결합이 필요할 시, `page.tsx`파일이나 컴포넌트 등의 `tsx`파일에서 결합합니다.

2024-05-20 09:23 UTC, mdgarden commented on types/kit.ts
> +export type KitCardsInfo = KitCardInfo[];
`export type KitCardsInfo = KitCardInfo[];` 이 줄은 있어도 되고 없어도 되는...작성 방법의 취향이라고 생각합니다.

2024-05-20 09:23 UTC, mdgarden commented on types/models.ts
> +import type { Prisma, VerificationToken } from '@prisma/client';
모든 테이블에 대해서 `findUnique`를 진행했을 때의 호출할 수 있는 모든 항목들입니다. 여기에 있는 항목들은 가급적이면 수정하지 말아주시고, 수정이 필요하거나 추가적인 항목이 필요할 때는 꼭 디코로 먼저 연락을 주세요.

원래는 별도의 타입작성이 필요하나, prisma의 기본 작성된 타입 파일을 사용하였습니다. 추후 프론트와 프리즈마가 분리될 때는 이 파일만 수정하면 됩니다.

2024-05-20 09:23 UTC, mdgarden commented on types/kit.ts
> -export type KitCardInfo = NonNullable<Prisma.Result<typeof prisma.kit, { select: typeof kitCardSelect }, 'findFirst'>>;
혹시 타입을 꼭 이렇게 작성해야하는 다른 이유가 있나요?

2024-05-20 09:23 UTC, mdgarden commented on app/kits/components/KitCard.tsx
> -interface KitCardProps extends KitCardInfo, React.ComponentPropsWithoutRef<typeof Card> {
저는 리액트에서 이 타입을 많이 안써봤는데,ComponentPropsWithoutRef이 타입을 꼭 사용해야하나요? 현재 제가 수정한 코드도 딱히 경고가 뜨지는 않는데, 어떤 점을 염두에 두고서 `ComponentPropsWithoutRef`를 사용하셨는지 궁금합니다.

2024-05-20 09:43 UTC, mdgarden commented on types/models.ts
> +import type { Prisma, VerificationToken } from '@prisma/client';
Prisma에서 불러온 `Kit`와 여기서 작성한 `KitModel`은 다음과 같은 차이가 있습니다.

```json
// Prisma.Kit

{
  "id": "ckxyz1234567890",
  "title": "Sample Kit",
  "description": "This is a sample kit",
  "tags": ["tag1", "tag2"],
  "thumbnailImage": "thumbnail.jpg",
  "rewardImage": "reward.jpg",
  "uploaderId": "ckxyz0987654321", // Prisma.Kit는 외래키로 참조하고 있는 유저 아이디만 반환합니다.
  "createdAt": "2024-05-20T12:00:00.000Z",
  "updatedAt": null,
  "deletedAt": null
}

// KitModel
{
  "id": "ckxyz1234567890",
  "title": "Sample Kit",
  "description": "This is a sample kit",
  "tags": ["tag1", "tag2"],
  "thumbnailImage": "thumbnail.jpg",
  "rewardImage": "reward.jpg",
  "uploaderId": "ckxyz0987654321",
  "createdAt": "2024-05-20T12:00:00.000Z",
  "updatedAt": null,
  "deletedAt": null,
  "uploader": { // 유저 정보, 스탬프 정보 등 외래키로 참고 하고 있는 정보도 전부 타입을 가져옵니다.
    "id": "ckxyz0987654321",
    "email": "uploader@example.com",
    "emailVerified": "2024-05-19T12:00:00.000Z",
    "profileImage": "profile.jpg",
    "nickname": "Uploader",
    "createdAt": "2024-05-18T12:00:00.000Z",
    "updatedAt": null,
    "deletedAt": null
  },
  "stamps": [
    {
      "id": "stamp1",
      "name": "First Stamp",
      "kitId": "ckxyz1234567890",
      "createdAt": "2024-05-20T12:00:00.000Z"
    },
    {
      "id": "stamp2",
      "name": "Second Stamp",
      "kitId": "ckxyz1234567890",
      "createdAt": "2024-05-20T12:00:00.000Z"
    }
  ],
  "rallies": [
    {
      "id": "rally1",
      "name": "First Rally",
      "kitId": "ckxyz1234567890",
      "createdAt": "2024-05-20T12:00:00.000Z"
    },
    {
      "id": "rally2",
      "name": "Second Rally",
      "kitId": "ckxyz1234567890",
      "createdAt": "2024-05-20T12:00:00.000Z"
    }
  ]
}


```

2024-05-20 10:48 UTC, 2chanhaeng requested changes
수고 많으셨습니다! :+1::+1::+1:
- 일부 파일에 오타가 있습니다. 수정 부탁드립니다!
- 마당님 질문 중 일부는 이전에 진행한 PR에 관련된 코멘트던데 해당 PR을 진행하던 시기가 아닌 현재 PR에서 여쭤보시는 이유가 있으실까요?
- type을 일일히 만들기 보단 [이런 방법](https://github.com/prisma/prisma/discussions/5526)은 어떠신가요? 백에서 `prisma generate` 로 생성된 타입을 패키지로 배포해서 프론트에서 설치해서 사용하는 방법인 것 같습니다.

2024-05-20 10:48 UTC, 2chanhaeng commented on types/kit.ts
> -export type KitCardInfo = NonNullable<Prisma.Result<typeof prisma.kit, { select: typeof kitCardSelect }, 'findFirst'>>;
'꼭 이렇게' 라는 건 어떤 방식을 문제 삼으시는 걸까요? 질문이 명확하지 않은 것 같습니다.
그리고 이 코드는 #31 에서 작성한 코드인데 해당 PR이 아닌 현재 PR에서 여쭤보시는 이유가 있으신가요?

2024-05-20 10:48 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +type KitCardProps = KitCardInfo & React.HTMLAttributes<HTMLDivElement>;
해당 인터페이스는 [희님의 코멘트](https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/17#discussion_r1599610367)를 반영하여 컴포넌트에서 사용할 props를 명시해둔 인터페이스입니다.

2024-05-20 10:48 UTC, 2chanhaeng commented on app/kits/page.tsx
> +import { KitCardsInfo } from '@/types/Kit';
대문자 K 오타가 있습니다. `types/Kit` -> `types/kit`

2024-05-20 10:57 UTC, 2chanhaeng commented on app/kits/page.tsx
> +  const response = await fetch('http://localhost:3000/api/kits', {
백엔드 분리를 생각하고 계신다면 백엔드 도메인과 경로를 분리해서 도메인을 상수로 두고 사용해야할 것 같습니다.

2024-05-20 11:07 UTC, mdgarden commented on types/kit.ts
> -export type KitCardInfo = NonNullable<Prisma.Result<typeof prisma.kit, { select: typeof kitCardSelect }, 'findFirst'>>;
아래에 있는 코멘트와 같은 이유이므로 여기서 답변을 드리고 아래 코멘트는 resolve하겠습니다.

> 그리고 이 코드는 https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/31 에서 작성한 코드인데 해당 PR이 아닌 현재 PR에서 여쭤보시는 이유가 있으신가요?

당시에는 타입이 어차피 바뀔 예정이어서 꼼꼼하게 살피지 않았던 부분입니다. 제가 생각하던 타입 운용 방식을 미리 전달해드려서 같은 이미지를 공유할 수 있었으면 더 좋았었겠네요....ㅠ

문제 삼는 것은 아니고,  제가 `NonNullable<Prisma.Result<typeof prisma.kit, { select: typeof kitCardSelect }, 'findFirst'>>;` 이라는 타입이 최종적으로 어떠한 타입을 반환하는지 파악하지 못해서 드린 질문입니다.(혹시 제가 파악하지 못한 의도가 다른 타입이 있다면 해당 내용을 반영해야하므로)

제가 새로 작성한 타입으로 대체가 가능하다면 이 질문은 스루하셔도 괜찮습니다!

2024-05-20 11:08 UTC, mdgarden commented on app/kits/page.tsx
> +import { KitCardsInfo } from '@/types/Kit';
타입을 다루는 파일은 대문자가 일반적인 것으로 알고 있습니다.

2024-05-20 11:10 UTC, mdgarden commented on app/kits/components/KitCard.tsx
> +type KitCardProps = KitCardInfo & React.HTMLAttributes<HTMLDivElement>;
넵 원래 작성해두셨던 props와 의도와 용도는 같습니다!

2024-05-20 12:46 UTC, blissful-y0 reviewed
defaultUser 관련해서 (cc: @2chanhaeng) 제가 기존에 진행된 논의를 제대로 팔로우업하지 못했데, defaultUser가 존재할 수 있는 경우는 guestUser 개념이 존재하는 경우뿐이고, 게스트 유저도 현재에는 애플이 정책을 바꾸어 더 이상 사용하지 않게 되었습니다
로그인 / 비로그인 state로 나누어 비로그인 유저가 로그인 페이지에 접근 시도할 경우 error를 반환하는 것이 맞는 것 같습니다
따라서 DefaultUser라는 타입명보다는 다른 이름이 필요할 것 같습니다

2024-05-20 12:46 UTC, blissful-y0 commented on app/kits/page.tsx
> +import { KitCardsInfo } from '@/types/Kit';
타입/컴포넌트/페이지/API의 경우 대문자로 처리합니다. 상수, custom hooks 등은 소문자로 처리합니다. resolve로 처리할게요.

2024-05-20 12:46 UTC, blissful-y0 commented on types/kit.ts
> +export type KitCardsInfo = KitCardInfo[];
선언한 타입과 상수 등이 많아질 경우 유연한 대응이 어려워집니다. KitCardInfo[]로 충분하다고 판단하여 해당 타입은 제외해도 좋을 것 같습니다.

2024-05-20 15:19 UTC, mdgarden commented on types/kit.ts
> +export type KitCardsInfo = KitCardInfo[];
반영하겠습니다!

2024-05-21 08:52 UTC, 2chanhaeng commented on app/kits/page.tsx
> +import { KitCardsInfo } from '@/types/Kit';
그럼 [`@/types/kit`](https://github.com/ZZIPSA/kkuk-kkuk-fe/pull/46/files#diff-3456281c71c884458c492193608263a7f06a1b881d94bda02d848be3add1d382)을 `@/types/Kit` 로 변경해야할 것 같습니다.

2024-05-21 08:59 UTC, 2chanhaeng commented on app/kits/components/KitCard.tsx
> +type KitCardProps = KitCardInfo & React.HTMLAttributes<HTMLDivElement>;
저도 처음엔 직접적인 명시는 안 했는데 희님께서 가독성 측면에서 직접 명시하는게 낫다고 하셔서 추가한 거라 희님께서 한 번 봐주시면 감사하겠습니다. @blissful-y0

2024-05-21 09:17 UTC, 2chanhaeng commented on types/kit.ts
> -export type KitCardInfo = NonNullable<Prisma.Result<typeof prisma.kit, { select: typeof kitCardSelect }, 'findFirst'>>;
제가 작성한 코드는 tsc가 다음과 같이 타입을 추측합니다.
<img width="551" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/b0dc9024-bcb9-453f-8922-dbac3a074b4f">

마당님께서 작성한 코드는 tsc가 다음과 같이 타입을 추측합니다.
<img width="552" alt="image" src="https://github.com/ZZIPSA/kkuk-kkuk-fe/assets/61987505/3622e29d-8e02-4da5-9150-07387699bd62">

2024-05-21 15:42 UTC, mdgarden commented on types/kit.ts
> -export type KitCardInfo = NonNullable<Prisma.Result<typeof prisma.kit, { select: typeof kitCardSelect }, 'findFirst'>>;
확실히 초무님이 작성하신 코드가 타입은 더 보기 쉽네요 🤔 요 내용은 제가 따로 더 파고들어보겠습니다.
우선 가져오는 타입은 같은 내용인 것을 확인했으므로 resolve하겠습니다.

2024-05-21 15:43 UTC, mdgarden commented on app/kits/page.tsx
> +import { KitCardsInfo } from '@/types/Kit';
제 로컬에서는 대문자 파일로 변경이 되어있는데 여기서는 반영이 안되어있네요! 머지 후에도 kit으로 되어있다면 핫픽스로 수정하겠습니다.

2024-05-21 15:45 UTC, merged