Issue/#40 특정 키트 조회 페이지 완성
ZZIPSA/kkuk-kkuk-fe pull request #52
Opened 2024-05-21 19:24 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #40 
특정 키트 조회 페이지 `/kits/[id]` 를 완성했습니다.

## 테스트 내용

### 리뷰어에게

### 체크리스트

- [ ] 셀프 리뷰를 진행했습니다.
- [ ] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [ ] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-05-22 10:05 UTC, mdgarden requested changes
프로젝트 초기 때부터 말씀드렸지만 컴포넌트의 사용이나 CSS 등은 잘 못보기 때문에(...) 클린 코드적인 면과 실기 화면에서 보이는 내용을 중점으로 리뷰해드렸습니다!

2024-05-22 10:05 UTC, mdgarden commented on components/KitCard/index.tsx
> +   * The unique identifier of the kit.
여기 `props`에만 주석을 다신 이유가 잇으신가요..?!

2024-05-22 11:49 UTC, 2chanhaeng commented on app/kits/[id]/components/StampsPreview/index.tsx
> +        {stamps.map(({ id, image }) => (
순서를 `order-`를 이용해 적용해뒀는데 `safelist`에 추가해 두지 않아서 적용이 되지 않고 있었습니다. 추가함으로써 해결했습니다. 1941b24d7ead9c2fc23a593b20d3e0d5b3894101

2024-05-22 11:49 UTC, 2chanhaeng commented on app/kits/[id]/page.tsx
> +        description={description ?? ''}
일단 표시하지 않도록 처리했습니다. 자세한 것은 하루님과 조율이 필요할 것 같습니다. a6713e3d7cc3d2f1035e6a1f61e726d57e8fbab1

2024-05-22 12:16 UTC, 2chanhaeng commented on app/kits/[id]/page.tsx
> +import { notFound } from 'next/navigation';
반영했습니다! 6fc7894fe26326c39bed2b91a86b78061ce46a1a

2024-05-22 12:16 UTC, 2chanhaeng commented on app/kits/[id]/components/RallyPreview/Stamp.tsx
> +interface StampProps extends RallyPreviewStamp {
타입 연산으로만 해결할 수 있는 경우는 `type`, 직접 props 를 명시해야하는 경우 `interface`를 사용합니다. `interface` 사용이 많이 불편하신가요?

2024-05-22 13:57 UTC, 2chanhaeng commented on app/kits/[id]/components/RallyPreview/Stamp.tsx
> +  const rows = Math.floor(order / 3);
어느 부분에서 grid를 쓰길 기대하셨는지 알려주실 수 있으신가요? 해당 컴포넌트는 스탬프 사진, 테두리, 완료 체크 표시를 위한 컴포넌트 입니다. 따라서 딱히 grid를 사용해야할 필요성을 느끼지 못했습니다. 대신 해당 컴포넌트를 `RallyPreview` 에서 배열할 때는 grid를 사용하고 있습니다.

2024-05-22 14:01 UTC, 2chanhaeng commented on app/kits/[id]/components/RallyPreview/Stamp.tsx
> +  const rows = Math.floor(order / 3);
`STAMP_BY_ROW` 를 분리해 해결했습니다!

2024-05-22 14:16 UTC, mdgarden commented on app/kits/[id]/components/RallyPreview/Stamp.tsx
> +interface StampProps extends RallyPreviewStamp {
아하, 설명과 링크 감사합니다!

2024-05-23 03:26 UTC, blissful-y0 approved these changes
Grid 제안드린 부분은 제가 사용성을 잘못 이해해서 이대로 해주시면 될거같습니다! 수고하셨어요~

2024-05-23 03:39 UTC, merged