#53 마이 페이지 완성
ZZIPSA/kkuk-kkuk-fe pull request #66
Opened 2024-05-23 15:25 UTC by 2chanhaeng

## 작업 내용

관련 이슈: #53 

- [x] 유저 페이지 레이아웃
  - [x] #54
  - [x] #56
- [x] 유저 페이지
  - [x] #55
  - [x] #61
  - [x] #62
  - [x] #63

## 테스트 내용

### 리뷰어에게

현재 DB 변경 중이라 로컬 DB로 실행해야 합니다.
`prisma/seed-user-rally.ts` 를 실행하고 테스트 부탁드립니다.

### 체크리스트

- [x] 셀프 리뷰를 진행했습니다.
- [x] 커밋 메세지를 컨벤션에 맞게 작성했습니다.
- [x] 테스트 내용에 기재된 항목에 대해서 실제로 테스트를 진행하고 동작을 확인했습니다.

2024-05-24 04:42 UTC, mdgarden requested changes
- PR 내용이 많아지면 리뷰어도 리뷰할 내용이 많아진다는 뜻이 됩니다. 지금과 같이 `PR은 기능 단위로 작성하기 vs PR에 들어간 파일이 많아져서 끊기 애매함` 이런 상황이 발생한다면 가볍게라도 좋으니 디코에 한마디 연락 해주시면 좋을 것 같습니다.
- 레이아웃 먼저 작업해달라고 부탁드렸는데, API까지 다 구현해주셨습니다. 의논되지 않은 부분에 대한 독자적인 작업은 기껏 열심히 작업해주셨음에도 불구하고 팀에 있어서는 손해가 됩니다. 작업 순서와 우선순위에 대해서는 나중에 대면으로 말씀드리겠습니다.

2024-05-24 04:42 UTC, mdgarden commented on app/api/my/joins/route.ts
> +  const data: JoinedRally[] = await prisma.rally.findMany({
joined라는 단어에 대해서 의견을 나누고 싶습니다. 개인적으로는 join은 '참여'라는 이미지가 강한데, RunningRally나 OpenedRally, ActivatedRally 등도 검토해보면 좋을 것 같습니다.

2024-05-24 04:42 UTC, mdgarden commented on app/api/my/completes/route.ts
> +  const data: CompletedRally[] = await prisma.rally.findMany({
사용자가 참여중인 랠리와 완료한 랠리를 API 각각 나눠서 구현해주셨습니다.
- 향후 랠리의 status가 더 많아질 가능성이 있다는 점
- API를 나눠서 가져와야할만큼 DB가 복잡하지않다는 점

이런 점을 고려하여 `my/rallies`로 API를 통합하고 파라미터로 원하는 정보만 필터링해서 가져오거나, `my/rallies`에서 불러온 전체 랠리를 프론트에서 분류하는 방법도 검토가능할 것 같습니다.

이미 나눠서 구현해주셨으니, 추후에 수정이 필요해지면 그 때 다시 검토해보겠습니다. 경로명만 수정해주세요.

2024-05-24 04:42 UTC, mdgarden commented on app/api/my/completes/route.ts
> +export async function GET() {
API의 경로명이 불명확합니다. 어떤 자원의 completes,joins를 가져오고 있는지 경로만으로 알기 어렵습니다.
`my/rallies/completes`,`my/rallies/joins`,`my/kits` 등으로 경로를 수정하는 것이 좋을 것 같습니다.

2024-05-24 04:42 UTC, mdgarden commented on app/my/(info)/completes/page.tsx
> +export default async function CompletesPage() {
`/my`라는 단일 페이지에서 탭으로 나누는 방법도 있었을 것 같은데, 어떤 점을 고려하셔서 탭마다 라우팅으로 나누셨는지 이유가 궁금합니다.

2024-05-24 04:42 UTC, mdgarden commented on app/my/(info)/components/MenuTabs/index.tsx
> +  console.log(path);
console.log 삭제 부탁드립니다.

2024-05-24 04:42 UTC, mdgarden commented on components/UserInfo/index.tsx
> +            <span className="text-2xl">𝕏</span>@{twitterAccount.userId}
확인을 덜 한 상태에서 드리는 코멘트입니다)
제가 로그인 작업을 했을 때는 OAuth2.0 로그인만으로는 트위터의 유저 아이디를 획득 할 수 없었습니다.(닉네임은 가능) 초무님께서 OAuth2.0으로 로그인 이후 트위터 유저 아이디를 취득한 경험이 있으시다면 공유 부탁드립니다.

2024-05-24 04:51 UTC, mdgarden commented on app/my/(info)/completes/page.tsx
> +export default async function CompletesPage() {
+)
프론트에 관해서 질문을 드리는건 잘잘못을 따지는 것이 아니고 제가 향후 프론트 작업에 참여하게 되므로 작업자분의 의도는 미리 파악해두고 싶어서 그렇습니다. 제가 잘못알고 있다면 잘못 알고 있다고 해주시면 되고, 특별한 이유가 없다면 그냥 없다고 해주시면 됩니다.

2024-05-24 08:28 UTC, 2chanhaeng reviewed
> - PR 내용이 많아지면 리뷰어도 리뷰할 내용이 많아진다는 뜻이 됩니다. 지금과 같이 PR은 기능 단위로 작성하기 vs PR에 들어간 파일이 많아져서 끊기 애매함 이런 상황이 발생한다면 가볍게라도 좋으니 디코에 한마디 연락 해주시면 좋을 것 같습니다.

죄송합니다. 처음 생각했을 때는 중복된 부분이 많아 변경될 부분이 별로 없다고 생각했는데 올려보니 제 생각보다 많아진 것 같습니다. 다음부터는 작업을 잘 분리하여 작업하겠습니다.

- 레이아웃 먼저 작업해달라고 부탁드렸는데, API까지 다 구현해주셨습니다. 의논되지 않은 부분에 대한 독자적인 작업은 기껏 열심히 작업해주셨음에도 불구하고 팀에 있어서는 손해가 됩니다. 작업 순서와 우선순위에 대해서는 나중에 대면으로 말씀드리겠습니다.

죄송합니다. 해당 코드는 단순 조회 등 구현이 어렵지 않은 작업이라 임시로 작성했던 API 였습니다. 다음부터는 제 권한 안에서만 작업하도록 하겠습니다. 제가 작성한 API는 어디까지나 임시용이므로 타입만 맞춰주신다면 편하게 제거하셔도 됩니다.

2024-05-25 12:56 UTC, mdgarden commented on components/UserInfo/index.tsx
> +            <span className="text-2xl">𝕏</span>@{twitterAccount.userId}
없으시다면 일부러 찾아보지 않으셔도 괜찮습니다! 해당 내용은 제가 찾아보겠습니다.

2024-05-25 12:57 UTC, mdgarden commented on app/my/(info)/completes/page.tsx
> +export default async function CompletesPage() {
확인했습니다! 설명 감사합니다.

2024-05-25 13:02 UTC, mdgarden commented on app/api/my/joins/route.ts
> +  const data: JoinedRally[] = await prisma.rally.findMany({
사용자라는건 엔드 유저 말씀하시는걸까요?
API의 사용자는 일반 엔드 유저들이 아닌 프론트 개발자들이 됩니다.
`joined`라는 단어는 크게 보았을 때는 `complete`도 포함하게 되므로 향후 혼선의 우려가 있습니다.
우선 파람으로 구별하도록 바꿔주신듯 하니 이 부분에 대한 자세한 논의는 패스하겠습니다.

2024-05-25 13:07 UTC, mdgarden commented on app/api/my/completes/route.ts
> +export async function GET() {
아마 대면으로 말씀드리기 전의 수정인 것 같습니다.
어제도 말씀드렸듯, API의 경로나 반환값에 대해서는 저와 꼭 상의 후 수정을 부탁드리겠습니다.
다른 유저의 정보 조회도 겸용하기 위해 변경하신 의도로 보이나, 외부에 공유되는 페이지와 마이페이지에서 보이는 정보가 다르므로 실제 프로덕션에서도 겸용으로 사용할지는 검토해보아야할 것 같습니다. 우선은 이 API로 진행하고, 추후 수정하도록 하겠습니다.

2024-05-26 11:26 UTC, mdgarden commented on types/User.ts
> +export type UserInfoResult = Pick<UserModel, 'profileImage' | 'nickname'> & {
#72 에서 유저 테이블의 일부 스키마가 수정되었습니다. 확인 후 수정이 필요한 곳은 #69 의 랠리 페이지와 함께 수정 후 푸쉬 부탁드립니다!

2024-05-26 11:46 UTC, 2chanhaeng commented on types/User.ts
> +export type UserInfoResult = Pick<UserModel, 'profileImage' | 'nickname'> & {
반영했습니다!

2024-05-27 06:02 UTC, mdgarden commented
현재 다음과 같은 사유로 로컬에서 실기 확인이 어렵습니다.

- API와 세션 사용 사이에 혼선이 있는 것 같습니다. 아래 파일에서 에러가 발생하여 마이페이지를 확인할 수 없습니다.

```ts
// components/UserInfo/index.ts

export default async function UserInfo({ variant = UserInfoVariant.default }: UserInfoProps) {
  const {
    data: { user }, // 여기서 에러 발생
  } = await auth();
  if (!user) return signIn();
  const api = `${process.env.API_URL}/api/user/${user.id}`;
```

다음과 같은 작업을 진행해주세요.
- 다른 사람의 로컬에서도 동작할 수 있도록 셀프 리뷰를 진행하고, 필요하다면 수정을 진행해주세요.
- 이번 PR뿐만 아니라 모든 PR에서의 셀프 리뷰는 동작확인을 필수로 진행해야합니다. PR작성 이후에도 수정사항이 있다면, 로컬에서 꼭 동작확인을 진행해주세요.

이대로 머지될 경우 백엔드 API와 맞물려 정상적으로 동작하지 않을 가능성이 매우 큽니다. 
백엔드 API가 미구현일 경우, 다음과 같은 방법으로 더미데이터를 활용하여 레이아웃을 구현해주세요.

```ts
const dummyUser = { id: '' };
const dummyUserInfo = { image: '', name: '테스트 유저', accounts: '', rallies: '' }; // 예시로 작성한 내용입니다. 더미데이터로 작성해야하는 내용이 많은 경우, 포스트맨에 있는 예시를 복붙해서 필요한만큼 수정해서 사용해주세요.

export default async function UserInfo({ variant = UserInfoVariant.default }: UserInfoProps) {
  // const {
  //   data: { user },
  // } = await auth();
  // if (!user) return signIn();
  // const api = `${process.env.API_URL}/api/user/${user.id}`;
  // const {
  //   data: { image, name, accounts, rallies },
  // }: { data: UserInfoResult } = await fetch(api).then((res) => res.json());
  // const twitterAccount = accounts.find(({ provider }) => provider === 'twitter');

  const user = dummyUser;
  const data = dummyUserInfo;
```

2024-05-27 07:46 UTC, 2chanhaeng commented
@mdgarden 해당 에러는 #73 및 #74 에서 해결했습니다. 번거로우실 수 있지만 해당 이슈 혹은 PR을 확인해주실 수 있으실까요?

2024-05-28 07:01 UTC, merged